[platformio]
default_envs = m5stack-atom

[env:m5stack-atom]
platform = espressif32@6.7.0
board = m5stack-atom
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit NeoPixel@^1.15.1
build_flags =
  -finput-charset=UTF-8
  -fexec-charset=UTF-8
